//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourseZertis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ExpiredTimeVL> ExpiredTimeVLs { get; set; }
        public virtual DbSet<EyeV> EyeVs { get; set; }
        public virtual DbSet<Isbranni> Isbrannis { get; set; }
        public virtual DbSet<JVLO> JVLOes { get; set; }
        public virtual DbSet<LessonVideoTime> LessonVideoTimes { get; set; }
        public virtual DbSet<LikeV> LikeVs { get; set; }
        public virtual DbSet<Modul> Moduls { get; set; }
        public virtual DbSet<Modul_userLevel> Modul_userLevel { get; set; }
        public virtual DbSet<Modules_Property> Modules_Property { get; set; }
        public virtual DbSet<Premium> Premiums { get; set; }
        public virtual DbSet<Premium_OrderId> Premium_OrderId { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Quiz_B_User_Answer> Quiz_B_User_Answer { get; set; }
        public virtual DbSet<Quiz_C_User_Answer> Quiz_C_User_Answer { get; set; }
        public virtual DbSet<Quiz_Option> Quiz_Option { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<User_Premium> User_Premium { get; set; }
        public virtual DbSet<User_Premium_Status> User_Premium_Status { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
        public virtual DbSet<Users_Certificates> Users_Certificates { get; set; }
        public virtual DbSet<ValitO> ValitOS { get; set; }
        public virtual DbSet<VideoL> VideoLs { get; set; }
        public virtual DbSet<VideoLEM> VideoLEMs { get; set; }
        public virtual DbSet<VideoXL> VideoXLs { get; set; }
        public virtual DbSet<Quiz_Content> Quiz_Content { get; set; }
        public virtual DbSet<Quiz_A_User_Answer> Quiz_A_User_Answer { get; set; }
    }
}
