//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourseZertis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpiredTimeVL
    {
        public int Id { get; set; }
        public int DefaultVLYear { get; set; }
        public int DefaultVLMonth { get; set; }
        public int DefaultVLDay { get; set; }
        public bool Enable { get; set; }
    }
}
