//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourseZertis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonVideoTime
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public double LessonXId { get; set; }
        public bool Status { get; set; }
    
        public virtual UserInfo UserInfo { get; set; }
    }
}
