//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourseZertis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Premium
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Premium()
        {
            this.User_Premium_Status = new HashSet<User_Premium_Status>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PremiumId { get; set; }
        public bool buy { get; set; }
        public int OrderId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Premium Premium { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Premium_Status> User_Premium_Status { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
