//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourseZertis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Premium_Status
    {
        public int Id { get; set; }
        public int User_PremiumId { get; set; }
        public string Status { get; set; }
    
        public virtual User_Premium User_Premium { get; set; }
    }
}
