//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineCourseZertis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoLEM
    {
        public int Id { get; set; }
        public double VideoXId { get; set; }
        public int Likes { get; set; }
        public int Eye { get; set; }
        public int minute { get; set; }
    
        public virtual VideoXL VideoXL { get; set; }
    }
}
